/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsKeywordsRouteImport } from './routes/settings.keywords'
import { Route as AccountsIdRouteImport } from './routes/accounts.$id'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiPublicApolloSyncAccountsRouteImport } from './routes/api/public/apollo-sync-accounts'

const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsKeywordsRoute = SettingsKeywordsRouteImport.update({
  id: '/settings/keywords',
  path: '/settings/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIdRoute = AccountsIdRouteImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApolloSyncAccountsRoute =
  ApiPublicApolloSyncAccountsRouteImport.update({
    id: '/api/public/apollo-sync-accounts',
    path: '/api/public/apollo-sync-accounts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pipeline': typeof PipelineRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/settings/keywords': typeof SettingsKeywordsRoute
  '/api/public/apollo-sync-accounts': typeof ApiPublicApolloSyncAccountsRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pipeline': typeof PipelineRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/settings/keywords': typeof SettingsKeywordsRoute
  '/api/public/apollo-sync-accounts': typeof ApiPublicApolloSyncAccountsRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pipeline': typeof PipelineRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/settings/keywords': typeof SettingsKeywordsRoute
  '/api/public/apollo-sync-accounts': typeof ApiPublicApolloSyncAccountsRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pipeline'
    | '/accounts/$id'
    | '/settings/keywords'
    | '/api/public/apollo-sync-accounts'
    | '/api/public/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pipeline'
    | '/accounts/$id'
    | '/settings/keywords'
    | '/api/public/apollo-sync-accounts'
    | '/api/public/ingest'
  id:
    | '__root__'
    | '/'
    | '/pipeline'
    | '/accounts/$id'
    | '/settings/keywords'
    | '/api/public/apollo-sync-accounts'
    | '/api/public/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PipelineRoute: typeof PipelineRoute
  AccountsIdRoute: typeof AccountsIdRoute
  SettingsKeywordsRoute: typeof SettingsKeywordsRoute
  ApiPublicApolloSyncAccountsRoute: typeof ApiPublicApolloSyncAccountsRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/keywords': {
      id: '/settings/keywords'
      path: '/settings/keywords'
      fullPath: '/settings/keywords'
      preLoaderRoute: typeof SettingsKeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$id': {
      id: '/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AccountsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/apollo-sync-accounts': {
      id: '/api/public/apollo-sync-accounts'
      path: '/api/public/apollo-sync-accounts'
      fullPath: '/api/public/apollo-sync-accounts'
      preLoaderRoute: typeof ApiPublicApolloSyncAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PipelineRoute: PipelineRoute,
  AccountsIdRoute: AccountsIdRoute,
  SettingsKeywordsRoute: SettingsKeywordsRoute,
  ApiPublicApolloSyncAccountsRoute: ApiPublicApolloSyncAccountsRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
